# Generated by Django 6.0.4 on 2026-04-09 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('FoodID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=32)),
                ('Brand', models.CharField(max_length=32)),
                ('TypeofFood', models.CharField(max_length=32)),
                ('Price', models.FloatField()),
                ('ItemWeight', models.FloatField()),
                ('ClassofFood', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Owners',
            fields=[
                ('OID', models.IntegerField(primary_key=True, serialize=False)),
                ('LastName', models.CharField(max_length=32)),
                ('Street', models.CharField(max_length=32)),
                ('City', models.CharField(max_length=32)),
                ('ZipCode', models.CharField(max_length=32)),
                ('State', models.CharField(max_length=16)),
                ('Age', models.IntegerField()),
                ('AnnualIncome', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('PetID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=32)),
                ('Age', models.IntegerField()),
                ('Street', models.CharField(max_length=32)),
                ('City', models.CharField(max_length=32)),
                ('ZipCode', models.CharField(max_length=32)),
                ('State', models.CharField(max_length=16)),
                ('TypeofPet', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Owns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.IntegerField()),
                ('PetAgeatOwnership', models.IntegerField()),
                ('PricePaid', models.IntegerField()),
                ('OID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pets.owners')),
                ('PetID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pets.pets')),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeofFood', models.CharField(max_length=32)),
                ('PetID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pets.pets')),
            ],
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Month', models.IntegerField()),
                ('Year', models.IntegerField()),
                ('Quantity', models.IntegerField()),
                ('FoodID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pets.foods')),
                ('OID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pets.owners')),
                ('PetID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pets.pets')),
            ],
        ),
    ]
